In [2]:
import torch
a = torch.randn((2, 2))
b = torch.randn((2, 2))
print(a)
print(b)

def show_vec(x, desc=""):
    print(desc)
    print(x)
    print(x.shape)

tensor([[ 0.8663, -1.4449],
        [ 0.1591, -0.2266]])
tensor([[ 1.7766, -0.9983],
        [ 0.1652, -0.4325]])


In [3]:
show_vec(torch.cat((a, b), dim=0), "cat")

cat
tensor([[ 0.8663, -1.4449],
        [ 0.1591, -0.2266],
        [ 1.7766, -0.9983],
        [ 0.1652, -0.4325]])
torch.Size([4, 2])


In [4]:
show_vec(torch.stack((a, b), dim=0), "stack")

stack
tensor([[[ 0.8663, -1.4449],
         [ 0.1591, -0.2266]],

        [[ 1.7766, -0.9983],
         [ 0.1652, -0.4325]]])
torch.Size([2, 2, 2])


In [5]:
show_vec(torch.mean(a, dim=0), "mean")

mean
tensor([ 0.5127, -0.8358])
torch.Size([2])
